apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner
  namespace: runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-runner
  template:
    metadata:
      labels:
        app: actions-runner
    spec:
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: ACCESS_TOKEN
          value: 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
        - name: RUNNER_SCOPE
          value: "repo"
        - name: LABELS
          value: self-hosted,Linux,X64,ubuntu-latest
        - name: REPO_URL
          value: https://github.com/lonegunmanb/ghlocalrunnertest
        - name: RUNNER_NAME
          value: ghrunner-localk8s

